/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Pantallas;

import com.mycompany.Service.CorreoService;
import com.mycompany.Service.EstudianteHobbieService;
import com.mycompany.Service.EstudianteService;
import com.mycompany.Service.HobbieService;
import com.mycompany.Service.ICorreoService;
import com.mycompany.Service.IEstudianteHobbieService;
import com.mycompany.Service.IEstudianteService;
import com.mycompany.Service.IHobbieService;
import com.mycompany.entities.Carrera;
import com.mycompany.entities.Correo;
import com.mycompany.entities.Estudiante;
import com.mycompany.entities.EstudianteHobbie;
import com.mycompany.entities.Hobbie;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author manue
 */
public class CrearUsuarioDao extends javax.swing.JFrame {

    private final IEstudianteService estudianteService;
    private final ICorreoService correoService;
    private final IHobbieService hobbieService;
    private final IEstudianteHobbieService estudianteHobbieService;
    private String fotoPath = null;

    private static final String PH_CORREO = "Correo...";
    private static final String PH_CONTRASENA = "Contraseña...";
    private static final String PH_CONFIRMAR = "Confirma La Contraseña...";
    private static final String PH_CARRERA = "Carrera...";
    private static final String PH_EDAD = "Ingresa tu edad...";
    private static final String PH_NOMBRE = "Nombre...";
    private static final String PH_APELLIDO = "Apellido...";
    private static final String PH_HOBBIES = "Ingresa Tus Hobbies (Separalos por comas)...";
    private static final String PH_INTERESES = "Ingresa Tus Intereses...";

    private void addPlaceholder(JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(Color.GRAY);
                }
            }
        });
    }

    /**
     * Creates new form CrearUsuarioDao
     */
    public CrearUsuarioDao() {
        initComponents();

        this.estudianteService = new EstudianteService();
        this.correoService = new CorreoService();
        this.hobbieService = new HobbieService();
        this.estudianteHobbieService = new EstudianteHobbieService();

        addPlaceholder(TextNombre, PH_NOMBRE);
        addPlaceholder(TextApellido, PH_APELLIDO);
        addPlaceholder(TextCorreo, PH_CORREO);
        addPlaceholder(TextContrasena, PH_CONTRASENA);
        addPlaceholder(TextConfirmar, PH_CONFIRMAR);
        addPlaceholder(TextCarrera, PH_CARRERA);
        addPlaceholder(TextEdad, PH_EDAD);
        addPlaceholder(TextHobbies, PH_HOBBIES);
        addPlaceholder(TextIntereses, PH_INTERESES);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblFoto = new javax.swing.JLabel();
        BtnAgregarFoto = new javax.swing.JButton();
        TextContrasena = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextApellido = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        TextConfirmar = new javax.swing.JTextField();
        TextCarrera = new javax.swing.JTextField();
        TextEdad = new javax.swing.JTextField();
        TextHobbies = new javax.swing.JTextField();
        TextIntereses = new javax.swing.JTextField();
        ButtonCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 249, 250));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga (1).png"))); // NOI18N
        lblFoto.setText("Sin Foto");
        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        desktopPane.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 210, 150));

        BtnAgregarFoto.setText("Agregar Foto");
        BtnAgregarFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarFotoActionPerformed(evt);
            }
        });
        desktopPane.add(BtnAgregarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        TextContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextContrasena.setForeground(new java.awt.Color(204, 204, 204));
        TextContrasena.setText("Contraseña...");
        TextContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContrasenaActionPerformed(evt);
            }
        });
        desktopPane.add(TextContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 330, 22));

        TextNombre.setForeground(new java.awt.Color(204, 204, 204));
        TextNombre.setText("Nombre...");
        TextNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        desktopPane.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, -1));

        TextApellido.setForeground(new java.awt.Color(204, 204, 204));
        TextApellido.setText("Apellido...");
        TextApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoActionPerformed(evt);
            }
        });
        desktopPane.add(TextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, -1));

        TextCorreo.setForeground(new java.awt.Color(204, 204, 204));
        TextCorreo.setText("Correo...");
        TextCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        desktopPane.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 330, -1));

        TextConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        TextConfirmar.setText("Confirma La Contraseña...");
        TextConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextConfirmarActionPerformed(evt);
            }
        });
        desktopPane.add(TextConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 330, -1));

        TextCarrera.setForeground(new java.awt.Color(204, 204, 204));
        TextCarrera.setText("Carrera...");
        TextCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, -1));

        TextEdad.setForeground(new java.awt.Color(204, 204, 204));
        TextEdad.setText("Ingresa tu edad...");
        TextEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEdadActionPerformed(evt);
            }
        });
        desktopPane.add(TextEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, -1));

        TextHobbies.setForeground(new java.awt.Color(204, 204, 204));
        TextHobbies.setText("Ingresa Tus Hobbies...");
        TextHobbies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHobbiesActionPerformed(evt);
            }
        });
        desktopPane.add(TextHobbies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 330, 40));

        TextIntereses.setForeground(new java.awt.Color(204, 204, 204));
        TextIntereses.setText("Ingresa Tus Intereses...");
        TextIntereses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 330, 40));

        ButtonCrearCuenta.setBackground(new java.awt.Color(0, 241, 242));
        ButtonCrearCuenta.setText("Crear Cuenta");
        ButtonCrearCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearCuentaActionPerformed(evt);
            }
        });
        desktopPane.add(ButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una foto");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (JPG, PNG)", "jpg", "jpeg", "png"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
            Image img = icono.getImage().getScaledInstance(
                    lblFoto.getWidth(),
                    lblFoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            lblFoto.setIcon(new ImageIcon(img));
            lblFoto.setText(""); // quita el texto “Sin foto”
            fotoPath = archivo.getAbsolutePath();
        }

    }//GEN-LAST:event_BtnAgregarFotoActionPerformed

    private void TextContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextContrasenaActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidoActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextConfirmarActionPerformed

    private void ButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearCuentaActionPerformed
        try {
            String nombre = TextNombre.getText().trim();
            String apellido = TextApellido.getText().trim();
            String correoStr = TextCorreo.getText().trim();
            String contrasena = TextContrasena.getText().trim();
            String confirmar = TextConfirmar.getText().trim();
            String carreraStr = TextCarrera.getText().trim().toUpperCase().replace(" ", "_");

            String hobbiesStr = TextHobbies.getText().trim();
            String interesesStr = TextIntereses.getText().trim();

            if (!contrasena.equals(confirmar) || contrasena.equals(PH_CONTRASENA)) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden o están vacías.", "Error de Contraseña", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (nombre.isEmpty() || nombre.equals(PH_NOMBRE) || apellido.isEmpty() || apellido.equals(PH_APELLIDO)) {
                JOptionPane.showMessageDialog(this, "Nombre y Apellido son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (correoStr.isEmpty() || correoStr.equals(PH_CORREO)) {
                JOptionPane.showMessageDialog(this, "Correo es obligatorio.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (carreraStr.isEmpty() || carreraStr.equals(PH_CARRERA.toUpperCase().replace(" ", "_"))) {
                JOptionPane.showMessageDialog(this, "Carrera es obligatoria.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int edad;
            String genero;
            String edadStr = TextEdad.getText().trim();

            try {
                if (edadStr.isEmpty() || edadStr.equals(PH_EDAD)) {
                    throw new NumberFormatException();
                }
                edad = Integer.parseInt(edadStr);
                if (edad <= 0 || edad >= 100) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException ex) {
                String edadInput = JOptionPane.showInputDialog(this, "Ingresa tu edad:", "Edad Obligatoria", JOptionPane.QUESTION_MESSAGE);
                if (edadInput == null || edadInput.isEmpty()) {
                    throw new Exception("Edad obligatoria.");
                }
                edad = Integer.parseInt(edadInput);
            }

            genero = JOptionPane.showInputDialog(this, "Ingresa tu género:", "Género Obligatorio", JOptionPane.QUESTION_MESSAGE);
            if (genero == null || genero.trim().isEmpty()) {
                throw new Exception("Género obligatorio.");
            }
            genero = genero.trim();

            Carrera carrera = Carrera.valueOf(carreraStr);
            String descripcion = interesesStr.equals(PH_INTERESES) ? "" : interesesStr;

            Estudiante nuevoEstudiante = new Estudiante();
            nuevoEstudiante.setNombre(nombre + " " + apellido);
            nuevoEstudiante.setContrasena(contrasena);
            nuevoEstudiante.setCarrera(carrera);
            nuevoEstudiante.setEdad(edad);
            nuevoEstudiante.setGenero(genero);
            nuevoEstudiante.setFotoUsuarioUrl(fotoPath);
            nuevoEstudiante.setDescripcion(descripcion);

            estudianteService.crearEstudiante(nuevoEstudiante);

            Correo nuevoCorreo = new Correo();
            nuevoCorreo.setCorreo(correoStr);
            nuevoCorreo.setEstudiante(nuevoEstudiante);
            correoService.crearCorreo(nuevoCorreo);

            if (!hobbiesStr.isEmpty() && !hobbiesStr.equals(PH_HOBBIES)) {
                String[] hobbiesArray = hobbiesStr.split(",");
                for (String hobbieNombreCompleto : hobbiesArray) {
                    String hobbieNombre = hobbieNombreCompleto.trim();

                    if (hobbieNombre.isEmpty()) {
                        continue;
                    }

                    List<Hobbie> hobbiesEncontrados = hobbieService.buscarPorNombre(hobbieNombre);
                    Hobbie hobbie;

                    if (hobbiesEncontrados.isEmpty()) {
                        hobbie = new Hobbie();
                        hobbie.setNombre(hobbieNombre);
                        hobbieService.crearHobbie(hobbie);
                    } else {
                        hobbie = hobbiesEncontrados.get(0);
                    }

                    if (!estudianteHobbieService.existeRelacion(nuevoEstudiante, hobbie)) {
                        EstudianteHobbie eh = new EstudianteHobbie();
                        eh.setEstudiante(nuevoEstudiante);
                        eh.setHobbie(hobbie);
                        estudianteHobbieService.crearEstudianteHobbie(eh);
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente. Ahora inicia sesión.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            IniciarSesionDao a = new IniciarSesionDao();
            a.setVisible(true);
            this.dispose();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La carrera ingresada no es válida. Carreras válidas: ING_SOFTWARE, ING_MECATRONICA, ING_ELECTRONICA, ING_QUIMICA, DISEÑO_GRAFICO", "Error de Carrera", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear la cuenta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonCrearCuentaActionPerformed

    private void TextEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEdadActionPerformed

    private void TextHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHobbiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHobbiesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarFoto;
    private javax.swing.JButton ButtonCrearCuenta;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextCarrera;
    private javax.swing.JTextField TextConfirmar;
    private javax.swing.JTextField TextContrasena;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextEdad;
    private javax.swing.JTextField TextHobbies;
    private javax.swing.JTextField TextIntereses;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables

}
