package Pantallas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author manue
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class ChatDao extends JFrame {

    private JPanel panelMensajes;
    private JScrollPane scrollPane;
    private JTextField campoTexto;
    private JButton btnEnviar;

    public ChatDao() {
        setTitle("Chat");
        setSize(400, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Panel donde van las burbujas
        panelMensajes = new JPanel();
        panelMensajes.setLayout(new BoxLayout(panelMensajes, BoxLayout.Y_AXIS));
        panelMensajes.setBackground(Color.WHITE);

        scrollPane = new JScrollPane(panelMensajes);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        add(scrollPane, BorderLayout.CENTER);

        // Panel inferior
        JPanel panelInput = new JPanel(new BorderLayout());
        campoTexto = new JTextField();
        btnEnviar = new JButton("Enviar");

        panelInput.add(campoTexto, BorderLayout.CENTER);
        panelInput.add(btnEnviar, BorderLayout.EAST);

        add(panelInput, BorderLayout.SOUTH);

        // Eventos
        btnEnviar.addActionListener(e -> enviarMensaje(true));
        campoTexto.addActionListener(e -> enviarMensaje(true));

        setVisible(true);
    }

    private void enviarMensaje(boolean esTuyo) {
        String texto = campoTexto.getText().trim();
        if (texto.isEmpty()) {
            return;
        }

        agregarBurbuja(texto, esTuyo);

        campoTexto.setText("");

        // Aquí simular un mensaje recibido
        // después de 1 segundo
        new Timer(1000, e -> {
            agregarBurbuja("Mensaje recibido: " + texto, false);
            ((Timer) e.getSource()).stop();
        }).start();
    }

    private void agregarBurbuja(String mensaje, boolean esTuyo) {

        JPanel burbuja = new JPanel();
        burbuja.setLayout(new BorderLayout());
        burbuja.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        JLabel labelMensaje = new JLabel("<html><body style='width: 200px'>" + mensaje + "</body></html>");
        labelMensaje.setOpaque(true);
        labelMensaje.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        if (esTuyo) {
            // Mensaje derecho (verde)
            labelMensaje.setBackground(new Color(185, 248, 180));
            burbuja.add(labelMensaje, BorderLayout.EAST);
        } else {
            // Mensaje izquierdo (gris)
            labelMensaje.setBackground(new Color(230, 230, 230));
            burbuja.add(labelMensaje, BorderLayout.WEST);
        }

        panelMensajes.add(burbuja);
        panelMensajes.revalidate();

        // Baja automáticamente hasta el último mensaje
        SwingUtilities.invokeLater(() -> {
            JScrollBar sb = scrollPane.getVerticalScrollBar();
            sb.setValue(sb.getMaximum());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatDao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
