/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Pantallas;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author manue
 */
public class CrearUsuarioDao extends javax.swing.JFrame {

    private void addPlaceholder(JTextField campo, String texto) {
        campo.setText(texto);
        campo.setForeground(Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(texto)) {
                    campo.setText("");
                    campo.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(texto);
                    campo.setForeground(Color.GRAY);
                }
            }
        });
    }

    /**
     * Creates new form CrearUsuarioDao
     */
    public CrearUsuarioDao() {
        initComponents();
        addPlaceholder(TextNombre, "Nombre...");
        addPlaceholder(TextApellido, "Apellido...");
        addPlaceholder(TextCorreo, "Correo...");
        addPlaceholder(TextContrasena, "Contraseña...");
        addPlaceholder(TextConfirmar, "Confirma La Contraseña...");
        addPlaceholder(TextCarrera, "Carrera...");
        addPlaceholder(TextSemestres, "Ingresa tu semestre...");
        addPlaceholder(TextHobbies, "Ingresa Tus Hobbies...");
        addPlaceholder(TextIntereses, "Ingresa Tus Intereses...");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblFoto = new javax.swing.JLabel();
        BtnAgregarFoto = new javax.swing.JButton();
        TextContrasena = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextApellido = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        TextConfirmar = new javax.swing.JTextField();
        TextCarrera = new javax.swing.JTextField();
        TextSemestres = new javax.swing.JTextField();
        TextHobbies = new javax.swing.JTextField();
        TextIntereses = new javax.swing.JTextField();
        ButtonCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 249, 250));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga (1).png"))); // NOI18N
        lblFoto.setText("Sin Foto");
        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        desktopPane.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 210, 150));

        BtnAgregarFoto.setText("Agregar Foto");
        BtnAgregarFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarFotoActionPerformed(evt);
            }
        });
        desktopPane.add(BtnAgregarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        TextContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextContrasena.setForeground(new java.awt.Color(204, 204, 204));
        TextContrasena.setText("Contraseña...");
        TextContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContrasenaActionPerformed(evt);
            }
        });
        desktopPane.add(TextContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 330, 22));

        TextNombre.setForeground(new java.awt.Color(204, 204, 204));
        TextNombre.setText("Nombre...");
        TextNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        desktopPane.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, -1));

        TextApellido.setForeground(new java.awt.Color(204, 204, 204));
        TextApellido.setText("Apellido...");
        TextApellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextApellidoActionPerformed(evt);
            }
        });
        desktopPane.add(TextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, -1));

        TextCorreo.setForeground(new java.awt.Color(204, 204, 204));
        TextCorreo.setText("Correo...");
        TextCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        desktopPane.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 330, -1));

        TextConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        TextConfirmar.setText("Confirma La Contraseña...");
        TextConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextConfirmarActionPerformed(evt);
            }
        });
        desktopPane.add(TextConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 330, -1));

        TextCarrera.setForeground(new java.awt.Color(204, 204, 204));
        TextCarrera.setText("Carrera...");
        TextCarrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 330, -1));

        TextSemestres.setForeground(new java.awt.Color(204, 204, 204));
        TextSemestres.setText("Ingresa tu semestre...");
        TextSemestres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextSemestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, -1));

        TextHobbies.setForeground(new java.awt.Color(204, 204, 204));
        TextHobbies.setText("Ingresa Tus Hobbies...");
        TextHobbies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextHobbies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 330, 40));

        TextIntereses.setForeground(new java.awt.Color(204, 204, 204));
        TextIntereses.setText("Ingresa Tus Intereses...");
        TextIntereses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        desktopPane.add(TextIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 330, 40));

        ButtonCrearCuenta.setBackground(new java.awt.Color(0, 241, 242));
        ButtonCrearCuenta.setText("Crear Cuenta");
        ButtonCrearCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearCuentaActionPerformed(evt);
            }
        });
        desktopPane.add(ButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una foto");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (JPG, PNG)", "jpg", "jpeg", "png"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());
            Image img = icono.getImage().getScaledInstance(
                    lblFoto.getWidth(),
                    lblFoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            lblFoto.setIcon(new ImageIcon(img));
            lblFoto.setText(""); // quita el texto “Sin foto”
        }

    }//GEN-LAST:event_BtnAgregarFotoActionPerformed

    private void TextContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextContrasenaActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextApellidoActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextConfirmarActionPerformed

    private void ButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearCuentaActionPerformed
        // TODO add your handling code here:
        IniciarSesionDao a = new IniciarSesionDao();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarFoto;
    private javax.swing.JButton ButtonCrearCuenta;
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextCarrera;
    private javax.swing.JTextField TextConfirmar;
    private javax.swing.JTextField TextContrasena;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextHobbies;
    private javax.swing.JTextField TextIntereses;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextSemestres;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables

}
